### ISSUE TITLE
Copy improvements to "HTTPS is broken. DNSChain fixes it."

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.com#29]
I'm going to split this up into two sections:

## 1. "HTTPS is broken"

A suggestion was received:

> I'd like to somehow differentiate between HTTPS (TLS/SSL), and the trust model it's generally used with (PKI). I have no flair for marketing, but...
> 
> The infrastructure that identifies secure websites is only as strong as its weakest link. Blockchain domains can be secured without broken trust models.

I personally do not see a way of improving this. The statement is accurate, and it links [to an explanation](https://www.eff.org/deeplinks/2011/10/how-secure-https-today) that elaborates on exactly what's broken about it.

We *could* say `X.509 is broken`, but I suspect that would be gibberish to 99% of our visitors, and therefore meaningless.

HTTPS is gibberish for enough people as it is.

So my personal inclination is to leave it be, but I welcome input on this.

## 2. "DNSChain fixes it"

Ryan Castellucci and I chatted over the phone and we both agreed that "DNSChain fixes it" could be improved.

While I don't see anything *inaccurate* about it, I do feel that we can do a better job of acknowledging and crediting the blockchains that DNSChain relies on.

So what say ya'll about changing that to `Blockchains fix it.`?

CC @ryancdotorg @john-light @ghyll @willstanley95 @SGrondin

**Comment by taoeffect** [comment]
Adding @WeMeetAgain @dionyziz @simondlr

**Comment by ryancdotorg** [comment]
To rehash my complaint about "HTTPS is broken" is that it will be taken at face value even if there's a link to a more nuanced explanation. What we can agree on is that we currently have a CA-based system that seemed to be the best that we could do 20 years ago but has serious flaws that are now becoming apparent. I think it's disingenuous to say that it's outright "broken", as it does do it's job the *vast* majority of the time. If you must have something "short and sweet", I'd object less to "HTTPS is flawed".

I don't think "DNSChain fixes it" or "Blockchains fix it" are good either. If someone reads that and doesn't look into the details they may think it solves site authentication in general rather than being limited to .bit and any other blockchain based TLDs that may be supported. Blockchain domains don't have a problem with CAs but they aren't a general solution to the problem.

Providing links to additional detail is great, but saying things that are likely to lead laypeople to think software has security properties it does not (regardless of intent) concerns me greatly.

**Comment by taoeffect** [comment]
> I think it's disingenuous to say that it's outright "broken", as it does do it's job the vast majority of the time. If you must have something "short and sweet", I'd object less to "HTTPS is flawed".

I am concerned that to call it only flawed would be to also detract from the urgency of the situation. If critically important software on which our infrastructure depends isn't behaving as it should, it would be irresponsible to downplay that.

I can't think of a good physical analogy. Brakes that fail 5% of the time would probably be considered broken, but at least they'd give you an indication that they weren't working. HTTPS gives you *no indication* when it's not working!

I can think of no more accurate term than "broken" for that situation.

> I don't think "DNSChain fixes it" or "Blockchains fix it" are good either. If someone reads that and doesn't look into the details they may think it solves site authentication in general rather than being limited to .bit and any other blockchain based TLDs that may be supported.

Hmm, the existence of systems that don't use (and therefore don't benefit from it), doesn't change the fact that it solves authentication in general for systems that do.

**Comment by ghyll** [comment]
> So what say ya'll about changing that to "Blockchains fix it."?
Though perhaps not the ideal final copy (@ryancdotorg has good points), I think "Blockchains fix it." is the better of the two candidates. It seems more accurate (at least one other project is using a Blockchain to address this https issue) as well as more enduring (projects may change names or merge/fork/etc). The implementation-neutral focus is also more in line with the educational focus of okT.

**Comment by ryancdotorg** [comment]
HTTPS has the following major failure cases (possibly some others that I'm forgetting):

* User clicking "please pwn me" when a browser detects and invalid certificate.
* [sslstrip](http://www.thoughtcrime.org/software/sslstrip/) style attacks.
* Client software not validating the server certificate properly.
* MitM proxy with locally installed CA (whether this is a "failure case" is debatable, though).
* Protocol downgrade attacks.
* Cryptographic attacks.
* CAs issuing certificates they shouldn't.

When you say "HTTPS is broken", you seem to be primarily talking about that last one. While it has happened, it seems to be very rare. There aren't any real statistics on this, but I the odds of any given HTTPS connection being hit with a illicitly issued certificate compare favorably with the odds of dying per mile driven in the US. This is perhaps not the best argument because the failures are not at all evenly distributed, but I think it's still useful. Even if I lived in a country willing to be caught red handed doing MitM attacks, I'd probably still be more worried about browser exploits. Is it flawed? Yes. But to simply call it "broken" strikes me as misleading.

**Comment by SGrondin** [comment]
So what say ya'll about changing that to Blockchains fix it.?

:+1:

**Comment by taoeffect** [comment]
> * User clicking "please pwn me" when a browser detects and invalid certificate.
> * [sslstrip](http://www.thoughtcrime.org/software/sslstrip/) style attacks.
> * Client software not validating the server certificate properly.
> * MitM proxy with locally installed CA (whether this is a "failure case" is debatable, though).
> * Protocol downgrade attacks.
> * Cryptographic attacks.
> * CAs issuing certificates they shouldn't.
> 
> When you say "HTTPS is broken", you seem to be primarily talking about that last one.

That's because none of those attacks are fundamental problems with the protocol, except for the last two. Cryptographic attacks apply to all cryptographic systems, so it wouldn't be fair to ding it for that.

> Is it flawed? Yes. But to simply call it "broken" strikes me as misleading.

On this point it seems like we are splitting hairs to me if we're arguing about the difference between "flawed" and "broken".

I think it really is fundamentally **broken**. That is my "expert opinion" on the matter, and I think I've presented a strong case for using that term in my previous comments.

**Comment by taoeffect** [comment]
Third-parties that have neither a relationship with website owners nor permission from them, have the ability to impersonate those websites.

For a protocol that purports to secure connections to websites, that is the very definition of broken.

**Comment by sdgathman** [comment]
I'm a fan of damning with faint praise.  I would say that HTTPS works pretty well - to the extent that you trust *every* CA that your browser installed for you to a) never make stupid technical mistakes (like using MD5 hashes) and b) never ever have a corrupt employee with enough access to help a client get a certificate processed that is "having trouble" because they don't in fact control the domain.  It's kind of like the credit card security model - where *every* vendor has to be secure, but the CC company would rather take the hits than impede transactions (since they make money per transaction).  

In the case of HTTPS, a CC company will in fact take the hit if you are buying something on the web with a CC.  For anything else, a technical or moral failure of any employee of any website you do anything significant with can put you in a world of hurt.

**Comment by taoeffect** [comment]
We just want to make sure that we preserve the impact, strength, urgency, and clarity of the message.

At the same time, the fewer words there are on the homepage, the better.

"HTTPS is broken. Blockchains fix it." seems like the best candidate so far.

We'll get this change up on the homepage this week hopefully, but of course we will remain receptive to concrete improvements / suggestions.

**Comment by ryancdotorg** [comment]
@domob1812 @JeremyRand can you please weigh in here?

**Comment by taoeffect** [comment]
Good idea, let's add more Namecoin folks: @phelixbtc @cassiniNMC

And maybe @shea256 @muneeb-ali@starkness can offer more perspectives/thoughts.

**Comment by taoeffect** [comment]
Good idea, let's add more Namecoin folks: @phelixbtc @cassiniNMC

And maybe @shea256 @muneeb-ali @starkness can offer more perspectives/thoughts.

**Comment by JeremyRand** [comment]
A few points:

1. Successful attacks by CA-issued certs make the news.  This suggests that such attacks are pretty rare.
2. I am unaware of a CA *willfully* issuing a bad cert.  CA's occasionally get compromised technically and have their keys stolen, but a CA has better security than most web servers and is subject to audits to verify that security.
3. CA's are a crappy architecture (and Namecoin has potential to be better), but I don't believe that CA certs are likely to be the attack vector used by most attackers.  Bad architecture != broken security.
4. Since we have the SSL Observatory, most attackers probably want an attack vector that doesn't immediately show up in the EFF database minutes to hours after it's deployed.  Leaving evidence lying around isn't something that attackers consider a plus, particularly when there are better attack vectors.
5. The Snowden docs suggest that the NSA regularly compromises HTTPS.  But no rogue NSA-controlled certs have shown up in the SSL Observatory.  That suggests that the NSA is simply stealing the servers' keys, because that's an easier and more preferable attack vector than subverting the CA system.

So, tl;dr, I agree with @ryancdotorg .

**Comment by taoeffect** [comment]
## Summary

I think it sounds like everyone is in agreement regarding "Blockchains fix it."

The only remaining point of contention is "HTTPS is broken." vs "HTTPS is flawed."

@ryancdotorg believes "HTTPS is broken." is misleading. I disagree for the reasons previously mentioned, probably most concisely put as this:

> Third-parties that have neither a relationship with website owners nor permission from them, have the ability to impersonate those websites.
> 
> For a protocol that purports to secure connections to websites, that is the very definition of broken.

"HTTPS is flawed", while accurate, to me sounds weird [and downplays the significance of the situation.](<#issuecomment-90810642>)

So, maybe there's a word somewhere in between "broken" and "flawed" we could use?

**Comment by taoeffect** [comment]
@JeremyRand wrote:

> Successful attacks by CA-issued certs make the news. This suggests that such attacks are pretty rare.

Not at all. The attacks are virtually impossible to detect, so they can be happening right now and no one would notice. Indeed, it took Google over two months to notice DigiCert on their servers, and that was with the help of having their own certs + browser.

> I am unaware of a CA willfully issuing a bad cert.

There was just one the other week that was all over the news.

> The Snowden docs suggest that the NSA regularly compromises HTTPS. But no rogue NSA-controlled certs have shown up in the SSL Observatory.

What's the evidence to support that claim? How would you be able to tell if it was "NSA-controlled"? And what does it matter if it's the NSA if someone else is doing it just as well? These last few points seem orthogonal to whether or not it's OK to consider the system [broken](#issuecomment-91025420).

**Comment by taoeffect** [comment]
Feedback from everyone tagged greatly appreciated on this. The more voices there are the clearer it will be what the consensus is.

Whatever the consensus ends up being, that's what we will do.

**Comment by taoeffect** [comment]
I'm also open to the possibility that only I consider "flawed" vs "broken" to be a meaningful difference. If the consensus ends up being that it doesn't matter (that flawed is as effective as broken), then I'm fine with changing it.

**Comment by pmconrad** [comment]
IMO the wording should be consistent.

I think we agree that x509/PKI is a broken concept, and that this has been abused in an (unknown) number of cases. However, x509 is just *one* aspect of HTTPS and still you want to call it "broken".

OTOH, we agree that blockchain tech fixes the x509/PKI issues. However, the fix can *only* be applied to .p2p domains, not to all domains out there, and still we call it a "fix".

IOW the "fix" only fixes a few specific instances of a system that is "broken" in one aspect. So either the fix is not really a fix, or the system is not really broken. :-)

**Comment by phelixbtc** [comment]
"The HTTPS trust system is broken. Blockchains can fix it."

**Comment by ryancdotorg** [comment]
> > I am unaware of a CA willfully issuing a bad cert.

> There was one just the other week that was all over the news.

I wouldn't say that CNNIC "willfully issued a bad cert" in the way Jeremy is talking about, however it *was* a *serious* fail, and an example of things that can go wrong with PKI. My understanding from reading the [Mozilla thread](https://groups.google.com/d/msg/mozilla.dev.security.policy/czwlDNbwHXM/cOdohhBrBTgJ) is that they issued a "test" intermediate CA (in violation of their own policies and CA Basic Requirements) with a validity period of only a few weeks to an incompetent company that promised to only use it for their own domain names but then accidentally ran a MitM attack on their own internal users, which all browsers explicitly allow anyway. Mozilla and Google have distrusted CNNIC as a result if this incident.

Anyway, what @phelixbtc said would be acceptable to me. In line with what @pmconrad said, I'll stop complaining if you say "PKI is broken." instead of "HTTPS is broken." I also wouldn't complain about "X.509 is broken.", but usually X.509 is used to refer to certificate structure, and you can't have TLS without that part of it.

**Comment by ryancdotorg** [comment]
Putting my concerns yet another way:

I consider it *unethical* to say something that will lead a significant number of people to think "Oh no, my email will be spied upon/my bank account will be drained/my computer will get a virus unless I use DNSChain", and I believe that leading with "HTTPS is broken" will have that result.

**Comment by WeMeetAgain** [comment]
I'm a fan of @phelixbtc 's contribution, maybe even going a little broader:
"The Web's trust system is broken, Blockchains can fix it.

**Comment by ryancdotorg** [comment]
@WeMeetAgain - that also works, and addresses @taoeffect's concern that "HTTPS is gibberish for enough people as it is."

**Comment by taoeffect** [comment]
**Thanks *everyone* for your comments and suggestions! Looks like you all indeed came up with a real improvement to the copy on the website.**

It is now more accurate, and yet it remain succinct. Thank you to everyone who participated!

The changes are now live on the website. Release notes and changes in 689a2ec.

**Comment by taoeffect** [comment]
Feel free to have a look at [the homepage](https://okturtles.com/). If there's anything else anyone sees that could use improvement, feel free to comment here (or open a new issue if you believe it's necessary).

Thanks again for all the feedback!
