### ISSUE TITLE
Update sitemap search results links

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.com#60]
### Problem

We're linking to some stuff we no longer want to link to, and not linking to stuff we do want to link to.

On Brave search:

![Screen Shot 2023-08-20 at 5 14 34 PM](https://github.com/okTurtles/okturtles.com/assets/138706/3c4b9bc8-87d0-45ab-a0c5-877470dcffe0)

- We don't want to link to the browser extension anymore

On DuckDuckGo:

![Screen Shot 2023-08-20 at 5 14 46 PM](https://github.com/okTurtles/okturtles.com/assets/138706/ace84a26-aa16-4b1e-8f2f-def8f28abfbc)

- We don't want to link to the forums anymore

### Solution

Figure out what needs to be modified/created to get the search results to show the right links.

I am guessing it is either the `<meta ..>` tags in the `<head>` section, or some special file like `sitemap.xml` or something

We want the following links to appear (or order of preference):

1. Shelter Protocol
2. Group Income
3. Blog
4. Donation page

**Comment by SebinSong** [comment]
@taoeffect 
It seems the common term the community use to refer to those child links of the search result is [`sitelinks` ](https://developers.google.com/search/docs/appearance/sitelinks).

and the topic of this issue can be split into below two.
1) Removing certain pages from being displayed as the search sitelinks.
2) Customising the search result so that sitelinks for particular pages we want to show up higher than the others.


There does seem to be [**a way**](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to achieve 1) by using a `<meta>` tag.

Regarding 2) however, according to multiple sources ([here](https://developers.google.com/search/docs/appearance/sitelinks#sitelinks-best-practices) and [here](https://firespring.my.salesforce-sites.com/printerpresence/articles/FAQ/The-XML-Sitemap-and-Sitemap-Priority)) I've found during the research, sitelinks are determined by the search engine's algorithm and apparently there is no way to control it unfortunately.

But at least there does seem to be a way we could give search engines **a hint** about which pages in the website we consider more important than others via creating `sitemap.xml` file and specifying `<priority></priority>` field in there,
according to [the official protocol documentation](https://www.sitemaps.org/protocol.html).

![image](https://github.com/okTurtles/okturtles.com/assets/17641213/ea107a94-bdb1-4b1c-a6f7-1fd908bce664)


I need to study how to create a proper `sitemap.xml` more thoroughly, so is it okay for me to send a PR for 1) first and then another subsequent PR for 2) once I do enough research about it?

thanks,

**Comment by taoeffect** [comment]
@SebinSong yeah no problem. We can consider this issue closed after both PRs are merged. 👍
